### PR TITLE
Update photoFrameFiller.py

### PR DESCRIPTION
**Pull request by Adrast**
Instead of counting the file list size, use build in python len() function to calculate it. Cleaner and faster

### CODE REVIEW

**Comment by therealrobster** [comment]
Hey there, sounds like a great idea.  Now this is my first ever pull request, so I'm sorry to ask but what's the next step?  Have you got actual code to implement or is it simply a suggestion?  Very new to this GIT stuff sorry.

**Comment by Adrast** [comment]
No worry, I'm new too! I've implemented it in the code

**Comment by therealrobster** [comment]
..and does that automatically get added to my original code?  Is there something I need to do or is it there?  Sorry, I just have never shared code like this.  Very cool experience.

**Review by therealrobster — APPROVED** [review]

**Comment by therealrobster** [comment]
Cancel that I found it.  Hey, that's some nice improvements.  Thank you.  What a great experience having someone out there find my code, use it, improve it, etc.  Thank you

**Pull request merged**
